CREATE TABLE PRODUCTS(
    ID INT PRIMARY KEY AUTO_INCREMENT NOT NULL,
    SKU VARCHAR(20) NOT NULL,
    NAME VARCHAR(255) NOT NULL,
    CATEGORY VARCHAR(10) NOT NULL,
    PRICE DECIMAL(23,8) NOT NULL,
    UNIQUE KEY IDX_UNIQ_PRODUCT_SKU (SKU)
);